/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

/**
 * @author Welinton
 */


public class TelaPrincipal extends javax.swing.JFrame {

    double num1 = 0;
    double num2 = 0;
    int operacao = 0;
    
    /** Tabela de Operações 
     * 
     * 1 - SOMA
     * 2 - SUBTRACAO
     * 3 - MULTIPLICACAO
     * 4 - DIVISAO
     * 
     */
    
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Display = new javax.swing.JTextField();
        jBotao7 = new javax.swing.JButton();
        jBotao8 = new javax.swing.JButton();
        jBotao9 = new javax.swing.JButton();
        jBotaoDivisao = new javax.swing.JButton();
        jBotao6 = new javax.swing.JButton();
        jBotao5 = new javax.swing.JButton();
        jBotao4 = new javax.swing.JButton();
        jBotaoClear = new javax.swing.JButton();
        jBotao1 = new javax.swing.JButton();
        jBotao2 = new javax.swing.JButton();
        jBotao3 = new javax.swing.JButton();
        jBotaoSubtracao = new javax.swing.JButton();
        jBotao0 = new javax.swing.JButton();
        jBotaoIgual = new javax.swing.JButton();
        jBotaoMais = new javax.swing.JButton();
        jBotaoMultiplicacao1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setBackground(new java.awt.Color(204, 204, 255));

        Display.setEditable(false);
        Display.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Display.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Display.setToolTipText("Utilize o Teclado a Baixo");

        jBotao7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBotao7.setText("7");
        jBotao7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotao7ActionPerformed(evt);
            }
        });

        jBotao8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBotao8.setText("8");
        jBotao8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotao8ActionPerformed(evt);
            }
        });

        jBotao9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBotao9.setText("9");
        jBotao9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotao9ActionPerformed(evt);
            }
        });

        jBotaoDivisao.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBotaoDivisao.setText("÷");
        jBotaoDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotaoDivisaoActionPerformed(evt);
            }
        });

        jBotao6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBotao6.setText("6");
        jBotao6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotao6ActionPerformed(evt);
            }
        });

        jBotao5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBotao5.setText("5");
        jBotao5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotao5ActionPerformed(evt);
            }
        });

        jBotao4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBotao4.setText("4");
        jBotao4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotao4ActionPerformed(evt);
            }
        });

        jBotaoClear.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBotaoClear.setText("C");
        jBotaoClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotaoClearActionPerformed(evt);
            }
        });

        jBotao1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBotao1.setText("1");
        jBotao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotao1ActionPerformed(evt);
            }
        });

        jBotao2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBotao2.setText("2");
        jBotao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotao2ActionPerformed(evt);
            }
        });

        jBotao3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBotao3.setText("3");
        jBotao3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotao3ActionPerformed(evt);
            }
        });

        jBotaoSubtracao.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBotaoSubtracao.setText("-");
        jBotaoSubtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotaoSubtracaoActionPerformed(evt);
            }
        });

        jBotao0.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBotao0.setText("0");
        jBotao0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotao0ActionPerformed(evt);
            }
        });

        jBotaoIgual.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBotaoIgual.setText("=");
        jBotaoIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotaoIgualActionPerformed(evt);
            }
        });

        jBotaoMais.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBotaoMais.setText("+");
        jBotaoMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotaoMaisActionPerformed(evt);
            }
        });

        jBotaoMultiplicacao1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBotaoMultiplicacao1.setText("x");
        jBotaoMultiplicacao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotaoMultiplicacao1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Calculadora By Welinton");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBotao4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBotao5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBotao1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBotao2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jBotaoIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBotao0, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jBotaoDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBotaoMais, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBotao3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBotaoSubtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBotao6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBotaoMultiplicacao1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Display, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBotao7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBotao8, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBotao9, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jBotaoClear, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Display, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBotao7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBotao8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBotao9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBotaoClear, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBotao4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBotao5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBotao6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBotaoMultiplicacao1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBotao1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBotao3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBotao2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBotaoSubtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBotao0, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBotaoIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBotaoMais, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBotaoDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBotao7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotao7ActionPerformed
        String t = Display.getText();
        Display.setText(t+"7");
    }//GEN-LAST:event_jBotao7ActionPerformed

    private void jBotao8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotao8ActionPerformed
        String t = Display.getText();
        Display.setText(t+"8");
    }//GEN-LAST:event_jBotao8ActionPerformed

    private void jBotao9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotao9ActionPerformed
        String t = Display.getText();
        Display.setText(t+"9");
    }//GEN-LAST:event_jBotao9ActionPerformed

    private void jBotaoDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotaoDivisaoActionPerformed
        if (operacao == 0){
            num1 = Double.parseDouble(Display.getText());
            operacao = 4;
            Display.setText(Display.getText()+"/");
        }
    }//GEN-LAST:event_jBotaoDivisaoActionPerformed

    private void jBotao6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotao6ActionPerformed
        String t = Display.getText();
        Display.setText(t+"6");
    }//GEN-LAST:event_jBotao6ActionPerformed

    private void jBotao5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotao5ActionPerformed
        String t = Display.getText();
        Display.setText(t+"5");
    }//GEN-LAST:event_jBotao5ActionPerformed

    private void jBotao4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotao4ActionPerformed
        String t = Display.getText();
        Display.setText(t+"4");
    }//GEN-LAST:event_jBotao4ActionPerformed

    private void jBotaoClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotaoClearActionPerformed
        num1 = 0;
        operacao = 0;
        Display.setText("");
    }//GEN-LAST:event_jBotaoClearActionPerformed

    private void jBotao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotao1ActionPerformed
        String t = Display.getText();
        Display.setText(t+"1");
    }//GEN-LAST:event_jBotao1ActionPerformed

    private void jBotao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotao2ActionPerformed
        String t = Display.getText();
        Display.setText(t+"2");
    }//GEN-LAST:event_jBotao2ActionPerformed

    private void jBotao3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotao3ActionPerformed
        String t = Display.getText();
        Display.setText(t+"3");
    }//GEN-LAST:event_jBotao3ActionPerformed

    private void jBotaoSubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotaoSubtracaoActionPerformed
        if (operacao == 0){
            num1 = Double.parseDouble(Display.getText());
            operacao = 2;
            Display.setText(Display.getText()+"-");
        }
    }//GEN-LAST:event_jBotaoSubtracaoActionPerformed

    private void jBotao0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotao0ActionPerformed
        String t = Display.getText();
        Display.setText(t+"0");
    }//GEN-LAST:event_jBotao0ActionPerformed

    private void jBotaoIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotaoIgualActionPerformed
        
        try{
            switch (operacao) {
                case 1: // Soma
                    {
                        int posicao = Display.getText().indexOf("+");
                        num2 = Double.parseDouble(Display.getText().substring(posicao+1));
                        double resultado = num1+num2;
                        Display.setText(Double.toString(resultado));
                        break;
                    }
                case 2: // Subtração 
                    {
                        int posicao = Display.getText().indexOf("-");
                        num2 = Double.parseDouble(Display.getText().substring(posicao+1));
                        double resultado = num1-num2;
                        Display.setText(Double.toString(resultado));
                        break;
                    }
                case 3: // Multiplicação
                    {
                        int posicao = Display.getText().indexOf("*");
                        num2 = Double.parseDouble(Display.getText().substring(posicao+1));
                        double resultado = num1*num2;
                        Display.setText(Double.toString(resultado));
                        break;
                    }
                case 4: // Divisão
                    {
                        int posicao = Display.getText().indexOf("/");
                        num2 = Double.parseDouble(Display.getText().substring(posicao+1));
                        if (num2 != 0 ){
                            double resultado = num1/num2;
                            Display.setText(Double.toString(resultado));
                        }       break;
                    }
                default:
                    break;
            }
            operacao = 0;
        }catch(NumberFormatException e){
            System.out.println("Sem valores para calcular...  Erro:"+e);
        }
    }//GEN-LAST:event_jBotaoIgualActionPerformed

    private void jBotaoMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotaoMaisActionPerformed
        if (operacao == 0){
            num1 = Double.parseDouble(Display.getText());
            operacao = 1;
            Display.setText(Display.getText()+"+");
        }
    }//GEN-LAST:event_jBotaoMaisActionPerformed

    private void jBotaoMultiplicacao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotaoMultiplicacao1ActionPerformed
        if (operacao == 0){
            num1 = Double.parseDouble(Display.getText());
            operacao = 3;
            Display.setText(Display.getText()+"*");
        }
    }//GEN-LAST:event_jBotaoMultiplicacao1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Display;
    private javax.swing.JButton jBotao0;
    private javax.swing.JButton jBotao1;
    private javax.swing.JButton jBotao2;
    private javax.swing.JButton jBotao3;
    private javax.swing.JButton jBotao4;
    private javax.swing.JButton jBotao5;
    private javax.swing.JButton jBotao6;
    private javax.swing.JButton jBotao7;
    private javax.swing.JButton jBotao8;
    private javax.swing.JButton jBotao9;
    private javax.swing.JButton jBotaoClear;
    private javax.swing.JButton jBotaoDivisao;
    private javax.swing.JButton jBotaoIgual;
    private javax.swing.JButton jBotaoMais;
    private javax.swing.JButton jBotaoMultiplicacao1;
    private javax.swing.JButton jBotaoSubtracao;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
